### ISSUE TITLE
structuration en un package

### ISSUE THREAD

**Issue by romainfrancois** [Geographie-cites/corpusminer-package#1]
- creation des répertoires typiques d'un package
  - déplacement des fonctions dans `R` 
  - commentaires `roxygen`

**Comment by romainfrancois** [comment]
J'ai rajouté le fichier `DESCRIPTION`. Quelques remarques: 

  - @DianeBeldame et @VincentGuyader, je nous ai mis en tant que `ctr`ce qui me semble le plus cohérent avec notre role. (dans `?person`)

```
"ctr"
(Contractor) Use for authors who have been contracted to write (parts of) the package 
and hence do not own intellectual property.
```

  - @chasset pourrais-tu rajouter ton adresse mail. Je ne l'ai pas trouvée. Par ailleurs cliquer sur `Courriel` http://pierre-olivier.chasset.net n'atterrit nulle part. 
  - @RCura : pareil, je n'ai pas trouvé d'adresse mail
  - @reyman: je te laisse remplir ta `person` 

  - @hcommenges je me suis basé sur la liste des personnes qui font partie de l'organisation `Geographie-cites` pour remplir la liste des auteurs. Je ne sais pas si cette liste est correcte. par exemple, j'ai ajouté @JusteRaimbault.

**Comment by RCura** [comment]
@romainfrancois : je ne suis pas dans ce projet, et @reyman non plus il me semble.
C'est donc @chasset , @hcommenges, @ClementineCttn  et @JusteRaimbault qui sont les `aut`

**Comment by romainfrancois** [comment]
Merci. @JusteRaimbault a corrigé deja. je peux closer.

**Comment by JulieVallee** [comment]
Idem pour moi, je ne pense pas être dans ce projet (même si je ne sais pas de quel projet il s'agit) 




De: "Robin Cura" <notifications@github.com> 
À: "Geographie-cites/corpusminer-package" <corpusminer-package@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Lundi 13 Février 2017 14:30:31 
Objet: Re: [Geographie-cites/corpusminer-package] structuration en un package (#1) 



[ https://github.com/romainfrancois | @romainfrancois ] : je ne suis pas dans ce projet, et [ https://github.com/reyman | @reyman ] non plus il me semble. 
C'est donc [ https://github.com/chasset | @chasset ] , [ https://github.com/hcommenges | @hcommenges ] , [ https://github.com/ClementineCttn | @ClementineCttn ] et [ https://github.com/JusteRaimbault | @JusteRaimbault ] qui sont les aut

**Comment by chapinux** [comment]
idem pour moi !

2017-02-13 14:39 GMT+01:00 JulieVallee <notifications@github.com>:

**Comment by mathieuleclaire** [comment]
Idem pour moi !
