### ISSUE TITLE
Package rmongodb

### ISSUE THREAD

**Issue by romainfrancois** [Geographie-cites/corpusminer-package#5]
Apparemment le package n'est plus sur CRAN. https://cran.r-project.org/web/packages/rmongodb/index.html

![capture d ecran 2017-02-13 a 14 34 59](https://cloud.githubusercontent.com/assets/2625526/22885427/b439183a-f1f9-11e6-97f7-407aeb8121d3.png)

Je ne sais as si n peut utiliser une version archivée, ce qui me semble risqué, ou peut être un autre package.

**Comment by romainfrancois** [comment]
Peut être `mongolite` (merci @DianeBeldame)

**Comment by JusteRaimbault** [comment]
ce package n'est plus maintenu en effet, et il n'est pas compatible avec mongo3.. vous pouvez éventuellement essayer de convertir avec d'autres passage d'interface avec mongo.
dans tous les cas je ne sais pas si c'est très utile de passer du temps sur cette partie de preprocessing, sachant que c'est entièrement dépendant (de manière artistique) de code java et python et qu'une version full python presque équivalente existe.

**Comment by romainfrancois** [comment]
@JusteRaimbault tu parles des fonctions présentes dans le `semantic.R` qui utilisent `rmongodb`? 

```
$ grep -R mongo *
DESCRIPTION:Imports: dplyr, igraph, rmongodb, utils
R/semantic.R:#' @description Construct semantic coocurrence graph directly from nw table in mongo.
R/semantic.R:#' @param mongohost : adress of mongodb
R/semantic.R:constructSemanticNetwork<-function(relevantcollection,kwcollection,nwcollection,edge_th,target,mongohost){
R/semantic.R:  mongo <- mongo.create(host=mongohost)
R/semantic.R:  relevant <- mongo.find.all(mongo,relevantcollection)
R/semantic.R:  dico <- mongo.find.all(mongo,kwcollection)
R/semantic.R:  edges <- mongo.find.all(mongo,nwcollection)
```

**Comment by JusteRaimbault** [comment]
oui en gros, les données mongo ne sont utilisées que dans le preprocessing de l'onglet 'citation network', qui consiste en les fichiers semantic.R et citation.R.
je l'ai mis dans le package au cas où, mais je ne sais pas si ça peut être d'une grande utilité dans ce contexte, car la collecte des données (java) est plus ou moins illégale, et la version R de construction du réseau et analyse de sensibilité n'est vraiment pas optimale par rapport au full python.
désolé il manque complètement la doc archi là dessus, car a priori on n'était pas parti pour inclure cette partie ; vous pouvez éventuellement laisser de côté dans un premier temps..

**Comment by romainfrancois** [comment]
@JusteRaimbault ok pas de soucis, j'ai mis le code en quarantaine

**Comment by JusteRaimbault** [comment]
ok c'est mieux comme ça.
on va voir mais une solution pour que tout soit un peut cohérent et ne pas enlever tout ce contenu au package, c'est de binder le java avec rjava (des jar sont déjà plus ou moins packagés) et de réécrire la partie python (qui n'est pas énorme juste un peu de NLP) en R ; sur des corpus de taille raisonnable la performance ne devrait pas poser de problème (là il y avait 2.10^6 abstracts). je vais voir si je trouve du temps prochainement.
