### ISSUE TITLE
CleanCorpus

### ISSUE THREAD

**Issue by romainfrancois** [Geographie-cites/corpusminer-package#6]
@hcommenges, tu as cette fonction: 

```r
CleanCorpus <- function(mystr){
  mystr <- str_to_lower(mystr)
  mystr <- gsub("[[:punct:]]", "", mystr)
  mystr <- gsub("[[:digit:]]", "", mystr)
  mystr <- gsub("\\s+", " ", str_trim(mystr))
  return(mystr)
}
```

Je me demande si ce n'est pas mieux de remplacer ponctuation `[:punct:]` et chiffres `[:digit:]` par un espace, pour les cas par exemple où on aurait pas d'espaces autour d'une virgule par exemple.

**Comment by hcommenges** [comment]
Oui c'est vrai ce serait probablement mieux.
