### ISSUE TITLE
Provenance de `CyberData$ARTICLES`

### ISSUE THREAD

**Issue by romainfrancois** [Geographie-cites/corpusminer-package#8]
Initialement, nous avions le fichier `CyberData.RData` avec les objets `NETKW` (utilisé par @hcommenges) et `ARTICLES` utilisé par @hcommenges et @ClementineCttn. 

Ces deux objets sont maintenant séparés en `overview_ARTICLES` et `NETKW`, stockés dans le dossier  `data/` du package. 

Maintenant que je comprends mieux ce que font les parties de l'application qui consomment l'objet `overview_ARTICLES`, j'aimerai avoir des précisions sur cet objet . 

 - si je ne m'abuse, on utilise qu'un subset des colonnes pour les applis overview et geo semantic, cad les colonnes: `id`, `authors`, `first_author`,  `citedby`, `citing`, `year` et toutes les colonnes `A_*`, `S_*`, et `L_*`. je suis donc tenté de ne garder que ces colonnes là. 

 - D'où viennent les colonnes `A_*`, `S_*` et `L_*`, est-ce que je peux les retrouver à partir d'une autre colonne de ce jeu de données. 

 - D'une manière générale, comment est-ce que ce jeu de données a été généré. Je cherche ici à limiter le doublon d'information entre cet objet et d'autres objets utilisés dans d'autres applications. Pour cela j'ai besoin de pouvoir revenir aux sources. 

@ClementineCttn est-ce que tu pourrais m'éclairer ?

**Comment by hcommenges** [comment]
Je pense que ces champs sont issus du LDA exécuté par @chasset en pré-processing. C'est lui qui pourra répondre précisément à ta question.

**Comment by chasset** [comment]
Cette description ne me dit rien

**Comment by ClementineCttn** [comment]
Bonjour! 
Désolée du delai je n'ai pas vu la notification pour cette question.
les colonnes A_* sont des booléens par pays ou un au moins des auteurs de l'article est affilié.
S_* sont des booléens par pays: 1 si le pays est sujet de l'article et 0 sinon.
L_* vaut pour chaque pays: 1 si le pays est sujet de l'article ET un au moins des auteurs y est affilié. Ca a ete fait comme ca pour gerer les multi-affiliations et multi-sujets.
Les donnees sources sont dans le fichier Geographie-cites/cybergeo20/R_Country_Wordcloud/articles2.csv et juste reformattees pour l'appli.
