### ISSUE TITLE
world

### ISSUE THREAD

**Issue by romainfrancois** [Geographie-cites/corpusminer-package#9]
Le pkg utilise dorénavant l'objet world, que j'ai créé en partant des fichiers `world*` du dossier des données. Je l'ai réduit de taille en utilisant `gSimplify`: 

```
> pryr::object_size(world)
1.96 MB
```

J'ai pour l'instant ce code pour le générer, il ya peut être moyen de faire plus simple: 

```
library(rgdal)
library(sp)
library(rgeos)
library(dplyr)

world_withZoom <- readOGR(dsn=system.file("data-raw/world_withZoom.shp", package = "corpusminer"), layer = "world_withZoom")

w <-readOGR(dsn= system.file( "data-raw/world.shp", package = "corpusminer"))
w <- w[ w@data$CNTR_ID %in% world_withZoom@data$CNTR_ID , ]

data <- w@data[, "CNTR_ID", drop = FALSE ]
data$NAME <- world_withZoom@data$NAME[ match(data$CNTR_ID, world_withZoom@data$CNTR_ID)  ]

w <- gSimplify(w, tol = .1)

world <- SpatialPolygonsDataFrame(w, data = data)
use_data( world, overwrite = TRUE )
```

J'aimerai si possible ne pas avoir à "trainer" tous les fichiers  `world.*` et `world_withZoom.*` : 

![capture d ecran 2017-05-11 a 16 05 21]
(https://cloud.githubusercontent.com/assets/2625526/25953438/a915e268-3663-11e7-8ab5-0f21a908f7ce.png)

**Comment by hcommenges** [comment]
Si tu as créé un objet world plus simple qui fait le job, tu pourrais le sauver en Rds et dégager tous les fichiers de format ESRI shapefile (ensemble des 4 ou 5 fichiers de même nom et d'extension .shp, .dbf, .prj etc.). Par ailleur le readOGR est bien plus lent que la lecture d'un Rds.

**Comment by romainfrancois** [comment]
oui j'ai deja un fichier `world.rda` dans le package, chargé automatiquement, qui reprends des polygones "gSimplifiés" pour les 167 pays: 

```
> dim( world@data )
[1] 167   2

> sample_n( world@data, 10 )
    CNTR_ID                        NAME
58       DO          Dominican Republic
194      SN                     Senegal
35       CA                      Canada
137      ML                        Mali
213      TT         Trinidad and Tobago
199      SY        Syrian Arab Republic
174      PS Occupied Palestinian Territ
209      TM                Turkmenistan
222      UZ                  Uzbekistan
179      RO                     Romania
```

J'enleve donc le reste. merci.
